services:
  webhook-hub-server:
    build: .
    container_name: webhook-hub-server
    ports:
      - "${PORT:-3005}:3005"
    env_file: .env
    volumes:
      - ./${TARGETS_FILE_PATH:-targets.json}:/app/${TARGETS_FILE_PATH:-targets.json}:ro
      - ./${PROVIDERS_FILE_PATH:-providers.json}:/app/${PROVIDERS_FILE_PATH:-providers.json}:ro
    networks:
      - external-network
    restart: unless-stopped

  webhook-hub-worker:
    build: .
    container_name: webhook-hub-worker
    command: ["node", "dist/worker.js"]
    env_file: .env
    volumes:
      - ./${TARGETS_FILE_PATH:-targets.json}:/app/${TARGETS_FILE_PATH:-targets.json}:ro
      - ./${PROVIDERS_FILE_PATH:-providers.json}:/app/${PROVIDERS_FILE_PATH:-providers.json}:ro
    networks:
      - external-network
    restart: unless-stopped
    healthcheck:
      disable: true

networks:
  external-network:
    name: ${EXTERNAL_NETWORK:-payment-webhook-hub-network}
    external: true
